### ISSUE TITLE
Can't use boss powers with this installed

### ISSUE THREAD

**Issue by Therzie** [andres-valdes/ReviveAllies#3]
Since new patch this plugin blocks the usage of Forsaken power usage.

**Comment by drpcken** [comment]
I too am seeing this issue.

**Comment by Lime18** [comment]
check this
[ReviveAllies.zip](https://github.com/andres-valdes/ReviveAllies/files/8239410/ReviveAllies.zip)

**Comment by andres-valdes** [comment]
Feel free to make a PR here, I don't really have any time to investigate and fix for the near future.

**Comment by andres-valdes** [comment]
Fixed by @BriianPowell on latest master and public version 0.1.0.
